<script lang="ts">
	import { TICK_RATE_SECONDS } from './sim_config';

	type InfoSection = 'About' | 'Data' | 'Methodology' | 'What is this?' | null;
	let open_section: InfoSection = null;

	function toggle(section: InfoSection) {
		open_section = open_section === section ? null : section;
	}

	function close() {
		open_section = null;
	}
</script>

<!-- Identity + buttons -->
<div class="absolute top-2 left-2 menu-panel">
	<div class="flex flex-wrap items-center gap-2">
		<!-- Title -->
		<div class="text-sm font-semibold tracking-wide">Live Satellite Orbits</div>

		<!-- Info buttons -->

		<button
			class="info-btn"
			data-selected={open_section === 'What is this?'}
			on:click={() => toggle('What is this?')}
		>
			What is this?
		</button>

		<button
			class="info-btn"
			data-selected={open_section === 'Data'}
			on:click={() => toggle('Data')}
		>
			Data
		</button>

		<button
			class="info-btn"
			data-selected={open_section === 'Methodology'}
			on:click={() => toggle('Methodology')}
		>
			Methodology
		</button>

		<button
			class="info-btn"
			data-selected={open_section === 'About'}
			on:click={() => toggle('About')}
		>
			About
		</button>
	</div>

	<!-- Anchored info panel -->
	{#if open_section}
		<!-- absolute top-full mt-3 left-1/2 -translate-x-1/2 -->
		<div
			class="
                absolute top-full mt-3 left-0
                w-104 max-h-[60vh]
                info-panel
            "
		>
			<!-- Header -->
			<div class="flex justify-between items-center mb-2">
				<h2 class="text-sm font-semibold capitalize">
					{open_section}
				</h2>
				<button class="text-xs info-btn" on:click={close}>x</button>
			</div>

			<!-- Content -->
			<div class="text-xs leading-relaxed overflow-y-auto space-y-2">
				{#if open_section === 'About'}
					<p>
						This visualization was built as an independent project to explore Earth's orbital
						environment and make satellite motion more intuitive to understand.
					</p>
					<p>Designed and built by a software engineer working in satellite and space systems.</p>
				{:else if open_section === 'Data'}
					<p>
						Satellite positions are derived from publicly available Two-Line Element (TLE) sets
						generated by the United States Space Force and disseminated by
						<a class="info-link" href="https://celestrak.org">Celestrak</a>.
					</p>
					<p>
						TLEs describe an orbit at a specific point in time and are widely used for satellite
						tracking, orbit propagation, and analysis.
					</p>
					<p>
						The satellites shown include all spacecraft listed in Celestrak's public
						<strong>active</strong> catalog.
						<a class="info-link" href="https://livesatelliteorbits.com">livesatelliteorbits.com</a>
						maintains an internal mirror of
						<a class="info-link" href="https://celestrak.org">Celestrak</a>
						TLE data, which is served directly to this web application.
					</p>
				{:else if open_section === 'Methodology'}
					<p>
						Orbits are propagated through time using the standard SGP4 orbital model via the
						MIT-licensed, open-source
						<a class="info-link" href="https://github.com/shashwatak/satellite-js">satellite.js</a>
						library.
					</p>
					<p>
						SGP4 propagation using TLEs loses accuracy the further it is extended from the TLE's
						generation time, typically this is on the order of a few to tens of kilometers over
						several days. This site is intended for visualization and educational purposes only, it
						is not intended for operational use.
					</p>
					<p>
						Satellite positions are propagated at a fixed tick rate of {TICK_RATE_SECONDS} seconds. Propagating
						all ~14,000 active satellites typically takes a few tens of milliseconds. To ensure smooth
						animation, positions are linearly interpolated between propagation ticks.
					</p>
					<p>
						The satellite positions shown are computed using TLEs cached by our server, and by your
						web browser's local storage. Updated TLEs are fetched from
						<a class="info-link" href="https://celestrak.org">Celestrak</a>
						approximately once per hour. Satellite orbit propagation is performed client-side in the web
						browser.
					</p>
					<p>
						Publicly available TLEs do not account for real-time propulsive maneuvers. If a
						satellite performs a maneuver, its updated orbit will not be reflected until a new TLE
						is published.
					</p>
				{:else if open_section === 'What is this?'}
					<p>
						This is a three-dimensional visualization of the Earth and the satellites orbiting it.
					</p>
					<p>
						The Earth and all satellite orbits are shown to-scale. Satellites are displayed in their
						current computed positions at this very moment, you can learn more about this
						computuation under <strong>Data</strong> and <strong>Methodology</strong>.
					</p>
					<p>
						This is not a live radar feed. It is a physics-based simulation using industry-standard
						orbital data and computational models used in real satellite operations.
					</p>
					<p>
						You can hover over and select individual satellites to view their orbits and details,
						and rotate or zoom the camera to explore Earth's orbital environment.
					</p>
				{/if}
			</div>
		</div>
	{/if}
</div>

<!-- Quiet disclaimer -->
<div
	class="
			absolute bottom-4 left-1/2 -translate-x-1/2
			text-[10px] text-cyan-200/50
		"
>
	For visualization and educational use only
</div>
